spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
jwt:
  secret: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml