spring:
  datasource:
    url: jdbc:mysql://${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
jwt:
  secret: ${JWT_SECRET}
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml