spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopping
    username: root
    password: admin
jwt:
  secret: djaksldhjkhfkjdkljasdkashdkjadhjkasshdjakdhkjadnamncbnmnzxbcnmzxasdlksajdklajdlkas
mybatis:
  configuration:
    map-underscore-to-camel-case: true